backend:
  name: git-gateway
media_folder: public/img
collections:
  - name: 'products'
    label: 'Produtos'
    create: true
    files:
      name: 'Produto'
      file: 'content/products.md'
      fields:
        - { label: 'Nome', name: 'name', widget: 'string' }
        - { label: 'Imagem', name: 'url', widget: 'string' }
        - {
            label: 'Valor',
            name: 'value',
            widget: 'number',
            valueType: 'float',
          }
        - { label: 'Tamanho', name: 'size', widget: 'string' }
        - { label: 'ReferÃªncia', name: 'ref', widget: 'number' }
